In [1]:
# Chapter 8: Data Wrangling - Join, Combine, and Reshape
import pandas as pd
import numpy as np

In [2]:
# Hierarchical Indexing
# enables to have multiple index levels on an axis
# provides a way to work with higher dimensional data in a lower dimensional form
data = pd.Series(np.random.uniform(size=9),
                 index=[["a","a","a","b","b","c","c","d","d"],
                        [1,2,3,1,3,1,2,2,3]])
data

a  1    0.119398
   2    0.477705
   3    0.575838
b  1    0.288784
   3    0.961433
c  1    0.798690
   2    0.618260
d  2    0.330345
   3    0.548694
dtype: float64

In [3]:
# Series with a Multiindex as its index, gap in the index means use the label directly above
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [4]:
# with hierarchically indexed object, partial indexing is possible, enabling to concisely select subsets of data
data["b"]

1    0.288784
3    0.961433
dtype: float64

In [5]:
data["b":"c"]

b  1    0.288784
   3    0.961433
c  1    0.798690
   2    0.618260
dtype: float64

In [6]:
data.loc[["b","d"]]

b  1    0.288784
   3    0.961433
d  2    0.330345
   3    0.548694
dtype: float64

In [7]:
# selection is even possible from an "inner" level; selecting all of the values having the value 2 from the second index level
data.loc[:,2]

a    0.477705
c    0.618260
d    0.330345
dtype: float64

In [8]:
# hierarchical indexing plays an important role in reshaping data and in group-based operations like pivot table
# rearranging data into DataFrame using .unstack()
data.unstack()

          1         2         3
a  0.119398  0.477705  0.575838
b  0.288784       NaN  0.961433
c  0.798690  0.618260       NaN
d       NaN  0.330345  0.548694

In [9]:
# the inverse operation of .unstack() is .stack()
data.unstack().stack()

a  1    0.119398
   2    0.477705
   3    0.575838
b  1    0.288784
   3    0.961433
c  1    0.798690
   2    0.618260
d  2    0.330345
   3    0.548694
dtype: float64

In [10]:
# with a DataFrame, either axis can have a hierarchical index
frame = pd.DataFrame(np.arange(12).reshape((4,3)),
                     index=[["a","a","b","b"],[1,2,1,2,]],
                     columns=[["Ohio","Ohio","Colorado"],
                              ["Green","Red","Green"]])
frame

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [11]:
# the hierarchical levels can have names (as strings or any Python objects); if so, these will show up in the console output
frame.index.names = ["key1","key2"]
frame.columns.names = ["state","color"]
frame

# these names supersede the name attribute, which is used only with single-level indexes; index names are not part of the row labels

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [12]:
# you can see how many levels an index has by accessing its .nlevels attribute:
frame.index.nlevels

2

In [13]:
# with partial column indexing you can similarly select groups of columns:
frame["Ohio"]

color      Green  Red
key1 key2
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [14]:
# a MultiIndex can be created by itself and then reused; 
# the columns in the preceding DataFrame with level names could also be created like below:
pd.MultiIndex.from_arrays([["Ohio","Ohio","Colorado"],
                           ["Green","Red","Green"]],
                          names=["state","color"])

MultiIndex([(    'Ohio', 'Green'),
            (    'Ohio',   'Red'),
            ('Colorado', 'Green')],
           names=['state', 'color'])

In [15]:
# Reordering and Sorting levels
# rearrange the order of the levels on an axis or sort the data by the valeus in one specific level
# .swaplevel() takes two level numvers or names and returns a new object with the levels interchanged (but data is otherwise unaltered)
frame.swaplevel("key1","key2")

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [16]:
# .sort_index() by default sorts the data using all the index levels; 
# but can choose to use only a single level or a subset of levels to sort by passing the level argument
frame.sort_index(level=1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [17]:
frame.swaplevel(0,1).sort_index(level=0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [18]:
# data selection performance is much better on heirarchically indexed objects if the index is sorted starting with the outermost level
# that is, the result of calling .sort_index(level=0) or .sort_index()

In [19]:
# Summary Statistics by Level
# many descriptive and summary statistics on DataFrame and Series have a level option in which you can specify the level you want to aggregate by on a particular axis
# can aggregate by level on either the rows or columns:
frame.groupby(level="key2").sum()

state  Ohio     Colorado
color Green Red    Green
key2
1         6   8       10
2        12  14       16

In [20]:
frame.groupby(level="color",axis="columns").sum()

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_13096\3295922660.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  frame.groupby(level="color",axis="columns").sum()

color      Green  Red
key1 key2
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

In [21]:
# Indexing with a DataFrames's columns
# moving columns from a DataFrame as the row index; alternatively, moving row index into DataFrame's columns
frame = pd.DataFrame({"a":range(7),"b":range(7,0,-1),
                      "c":["one","one","one","two","two","two","two"],
                      "d":[0,1,2,0,1,2,3]})
frame

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [22]:
# DataFrame's .set_index() will create a new DataFrame using one or more of its columns as the index:
frame2 = frame.set_index(["c","d"])
frame2

       a  b
c   d
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [23]:
# by default,the columns are removed from the DataFrame, though you can leave them in by passing drop=False to .set_index():
frame.set_index(["c","d"],drop=False)

       a  b    c  d
c   d
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [24]:
# on the other hand, .reset_index() does the opposite;
# the hierarchical index levels are moved into the columns
frame2.reset_index()

     c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

In [25]:
# Combining and Merging Datasets

In [26]:
# methods of combining data objects in pandas

# 1. pandas.merge : Connect rows in DataFrames baed on one or more keys; SQL JOIN method
# 2. pandas.concat : Cancatenate or "stack" objects together along an axis
# 3. combine_first : Splice together overlapping dat to fill in missing values in one object with value from another

In [27]:
# Database-Style DatFrame Joins
# pd.merge() is the main entry point
df1 = pd.DataFrame({"key":["b","b","a","c","a","a","b"],
                    "data1":pd.Series(range(7),dtype="Int64")})
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [28]:
df2 = pd.DataFrame({"key":["a","b","d"],
                    "data2":pd.Series(range(3),dtype="Int64")})
df2

  key  data2
0   a      0
1   b      1
2   d      2

In [29]:
# using Int64 extention type for nullable integers
# example of "many-to-one-join" : df1's multiple rows of "a" and "b" whereas df2 has only one corresponding row for each
pd.merge(df1,df2)

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [30]:
# note that for above example, didn't specify which column to join on
# if not specified, pd.merge() uses the overlapping column names as keys - it's a good practice to specify explicitly
pd.merge(df1,df2,on="key")

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [31]:
# in general, the order of column output is unspecified
# if column names are different in each object, can specify them separately:
df3 = pd.DataFrame({"lkey":["b","b","a","c","a","a","b"],
                    "data1":pd.Series(range(7),dtype="Int64")})
df3

  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [32]:
df4 = pd.DataFrame({"rkey":["a","b","d"],
                    "data2":pd.Series(range(3),dtype="Int64")})
df4

  rkey  data2
0    a      0
1    b      1
2    d      2

In [33]:
pd.merge(df3,df4,left_on="lkey",right_on="rkey")

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    a      4    a      0
4    a      5    a      0
5    b      6    b      1

In [34]:
# "c" and "d" values and assiciated data are missing from the result above
# by default, pd.merge() does an "INNER JOIN"; the keys in the result are the intesection, or common set
# other possible options are "left", "right", and "outer" (union of the keys)
pd.merge(df1,df2,how="outer")

  key  data1  data2
0   a      2      0
1   a      4      0
2   a      5      0
3   b      0      1
4   b      1      1
5   b      6      1
6   c      3   <NA>
7   d   <NA>      2

In [35]:
pd.merge(df3,df4,left_on="lkey",right_on="rkey",how="outer")

  lkey  data1 rkey  data2
0    a      2    a      0
1    a      4    a      0
2    a      5    a      0
3    b      0    b      1
4    b      1    b      1
5    b      6    b      1
6    c      3  NaN   <NA>
7  NaN   <NA>    d      2

In [36]:
# in outer join, rows from the left or right DataFrame objects that do not match will appear with NA

In [37]:
# Different join types with the "how" argument
# how="inner" : Use only the key combinations observed in both tables
# how="left" : Use all key combinations found in the left table
# how="right" : Use all key combinations found in the right table
# how="outer" : Use all key combinations observed in both tables together

In [38]:
# Many-to-many merges from Cartesian product of the matching keys
df1 = pd.DataFrame({"key":["b","b","a","c","a","b"],
                    "data1":pd.Series(range(6),dtype="Int64")})
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [39]:
df2 = pd.DataFrame({"key":["a","b","a","b","d"],
                    "data2":pd.Series(range(5),dtype="Int64")})
df2

  key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [40]:
pd.merge(df1,df2,on="key",how="left")

   key  data1  data2
0    b      0      1
1    b      0      3
2    b      1      1
3    b      1      3
4    a      2      0
5    a      2      2
6    c      3   <NA>
7    a      4      0
8    a      4      2
9    b      5      1
10   b      5      3

In [41]:
# since there were three "b" rows in the left DF and two in the right one, there are six "b" rows in the result
# the join method passed to the how keyword argument affects only the distinct key values appearing in the result:
pd.merge(df1,df2,how="inner")

  key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   a      2      0
5   a      2      2
6   a      4      0
7   a      4      2
8   b      5      1
9   b      5      3

In [42]:
# to merge with multiple keys, pass a list of column names:
left = pd.DataFrame({"key1":["foo","foo","bar"],
                     "key2":["one","two","one"],
                     "lval":pd.Series([1,2,3],dtype='Int64')})
left

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [43]:
right = pd.DataFrame({"key1":["foo","foo","bar","bar"],
                      "key2":["one","one","one","two"],
                      "rval":pd.Series([4,5,6,7],dtype='Int64')})
right

  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [44]:
pd.merge(left,right,on=["key1","key2"],how="outer")

  key1 key2  lval  rval
0  bar  one     3     6
1  bar  two  <NA>     7
2  foo  one     1     4
3  foo  one     1     5
4  foo  two     2  <NA>

In [45]:
# to determine which key combinations will appear in the result depending on the choice of merge method;
# think of the multiple keys as forming an array of tuples to be used as a single join key
# when joining columns on columns, indexes on the passed DF objects are discarded; if preservation needed, use .reset_index() to append the index to columns
# last issue to consider in merge operations is the treatment of overlapping column names
pd.merge(left,right,on="key1")

  key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [46]:
# you can either rename axis indexes or,
# pd.merge() has a suffixes option for specifying strings to append to overlapping names in the left and right DataFrame objects:
pd.merge(left,right,on="key1",suffixes=("_left","_right"))

  key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

In [47]:
# .pd.merge() function arguments

# left : DataFrame to be merged on the left side
# right : DataFrame to be merged on the right side
# how : Type of join to apply; on eof "inner", "outer", "left", or "right"; defaults to "inner"
# on : Column names to join on; Must be found in both DataFrame objects;
#      If not specified and no other join keys given, will use the intersection of the column names in left and right as the join keys
# left_on : Columns in left DataFrame to use as join keys; Can be a single column name or a list of column names
# right_on : Analogous to left_on for right DataFrame
# left_index : Use row index in left as its join key (or keys, if a MultiIndex)
# right_index : Analogous to left_index
# sort : Sort merged data lexicographically by join keys; False by default
# suffixes : Tuple of string values to append to column names in case of overlap; defaults to ("_x","-y") (e.g., "data_x","data_y")
# copy : If False, avlid copying data into resulting data structure in some exceptional cases; by default always copies
# validate : Verifies if the merge is of the specified type, whether one-to-one, one-to-many, or many-to-many
# indicator : Adds a special column _merge that indicates the source of each row; 
#             values will be "left_only", "right_only", or "both" based on the origin of the joined data in each row

In [48]:
# Merging on Index

# in some cases, the merge key(s) in a DF will be found in its index (row labels);
# can pass left_index=True or right_index=True (or both) to indicate that the index should be used as the merge key:

left1 = pd.DataFrame({"key":["a","b","a","a","b","c"],
                      "value":pd.Series(range(6),dtype="Int64")})
left1

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [49]:
right1 = pd.DataFrame({"group_val":[3.5,7]},index=["a","b"])
right1

   group_val
a        3.5
b        7.0

In [50]:
pd.merge(left1,right1,left_on="key",right_index=True)

  key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0

In [51]:
# looking carefully, index values from left1 have been preserved, the indexes of the input DF objects are dropped
# because the index of right1 is unique, this "many-to-one" merge (with default how="inner") can preserve the index values from left1

In [52]:
# since the default pd.merge() is to intersect the join keys, can instead form the union of them with an outer join:
pd.merge(left1,right1,left_on="key",right_index=True,how="outer")

  key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [53]:
# with hierarchically indexed data, joining on index is equivalent to a multiple-key merge:
lefth = pd.DataFrame({"key1":["Ohio","Ohio","Ohio","Nevada","Nevada"],
                      "key2":[2000,2001,2002,2001,2002],
                      "data":pd.Series(range(5),
                                       dtype="Int64")})
lefth

     key1  key2  data
0    Ohio  2000     0
1    Ohio  2001     1
2    Ohio  2002     2
3  Nevada  2001     3
4  Nevada  2002     4

In [54]:
righth_index = pd.MultiIndex.from_arrays(
                [
                    ["Nevada","Nevada","Ohio","Ohio","Ohio","Ohio"],
                    [2001,2000,2000,2000,2001,2002]
                ])
righth_index

MultiIndex([('Nevada', 2001),
            ('Nevada', 2000),
            (  'Ohio', 2000),
            (  'Ohio', 2000),
            (  'Ohio', 2001),
            (  'Ohio', 2002)],
           )

In [55]:
righth = pd.DataFrame({"event1":pd.Series([0,2,4,6,8,10],dtype="Int64",
                                          index=righth_index),
                       "event2":pd.Series([1,3,5,7,9,11],dtype="Int64",
                                          index=righth_index)})
righth

             event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [56]:
# in this case, you have to indicate multiple columns to merge on as a list (note the handling of duplicate index values with how="outer"):
pd.merge(lefth,righth,left_on=["key1","key2"],right_index=True)

     key1  key2  data  event1  event2
0    Ohio  2000     0       4       5
0    Ohio  2000     0       6       7
1    Ohio  2001     1       8       9
2    Ohio  2002     2      10      11
3  Nevada  2001     3       0       1

In [57]:
pd.merge(lefth,righth,left_on=["key1","key2"],right_index=True,how="outer")

     key1  key2  data  event1  event2
4  Nevada  2000  <NA>       2       3
3  Nevada  2001     3       0       1
4  Nevada  2002     4    <NA>    <NA>
0    Ohio  2000     0       4       5
0    Ohio  2000     0       6       7
1    Ohio  2001     1       8       9
2    Ohio  2002     2      10      11

In [58]:
# using the indexes of both sides of the merge is also possible
left2 = pd.DataFrame([[1.,2.],[3.,4.],[5.,6.]],
                     index=["a","c","e"],
                     columns=["Ohio","Nevada"]).astype("Int64")
left2

   Ohio  Nevada
a     1       2
c     3       4
e     5       6

In [59]:
right2 = pd.DataFrame([[7.,8.],[9.,10.],[11.,12.],[13,14]],
                      index=["b","c","d","e"],
                      columns=["Missouri","Alabama"]).astype("Int64")
right2

   Missouri  Alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [60]:
pd.merge(left2,right2,how="outer",left_index=True,right_index=True)

   Ohio  Nevada  Missouri  Alabama
a     1       2      <NA>     <NA>
b  <NA>    <NA>         7        8
c     3       4         9       10
d  <NA>    <NA>        11       12
e     5       6        13       14

In [61]:
# DataFrame has a .join() instance method to simplify merging by index
# can also be used to combine many DataFrame objects having the same or similar indexes but nonoverlapping columns

left2.join(right2,how="outer")

   Ohio  Nevada  Missouri  Alabama
a     1       2      <NA>     <NA>
b  <NA>    <NA>         7        8
c     3       4         9       10
d  <NA>    <NA>        11       12
e     5       6        13       14

In [62]:
# DF's .join() performs a left join on the join keys by default
# .join() also supports joining the indexes of the passed DF on one of the columns of the calling DF:
# joining on key

left1.join(right1,on="key")

  key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [63]:
# for simple index-on-index merges, can pass a list of DFs to join as an alternative to using the more general .pd.concat()

another = pd.DataFrame([[7.,8.],[9.,10.],[11.,12.],[16.,17.]],
                       index=["a","c","e","f"],
                       columns=["New York","Oregon"])
another

   New York  Oregon
a       7.0     8.0
c       9.0    10.0
e      11.0    12.0
f      16.0    17.0

In [64]:
left2.join([right2,another])

   Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2      <NA>     <NA>       7.0     8.0
c     3       4         9       10       9.0    10.0
e     5       6        13       14      11.0    12.0

In [65]:
left2.join([right2,another],how="outer")

   Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2      <NA>     <NA>       7.0     8.0
c     3       4         9       10       9.0    10.0
e     5       6        13       14      11.0    12.0
b  <NA>    <NA>         7        8       NaN     NaN
d  <NA>    <NA>        11       12       NaN     NaN
f  <NA>    <NA>      <NA>     <NA>      16.0    17.0

In [66]:
# Concatenating Along an Axis

# another kind of data combination operation is referred to interchangeably as concatenation or staking
# numpy arrays concatenating

arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
np.concatenate([arr,arr],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [68]:
# for Series and DFs, having labeled axes enable you to further generalize array concatenation
# for concatenation there are additional concerns:
# if the objects are indexed differently on the other axes, should we combine the distinct elemnts in these axes or use only the values in common?
# do the concatenated chunks of data need to be identifiable as such in the resulting object?
# does the "concatenation axis" contain data that needs to be preserved? In many cases, the default integer labels in a DF are best discarded during concatenation
# the .concat() provides a consistent way to address each of the questions above.

In [69]:
# Suppose we have 3 Series with no index overlap:

s1 = pd.Series([0,1],index=["a","b"],dtype="Int64")
s2 = pd.Series([2,3,4],index=["c","d","e"],dtype="Int64")
s3 = pd.Series([5,6],index=["f","g"],dtype="Int64")

In [70]:
s1

a    0
b    1
dtype: Int64

In [71]:
s2

c    2
d    3
e    4
dtype: Int64

In [72]:
s3

f    5
g    6
dtype: Int64

In [73]:
# calling pd.concat() with these objects in a list glues together the values and indexes:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: Int64

In [74]:
# by defualt, pd.concat() works along axis="index", producing another Series
# if pass axis="columns" the result will instead be a DataFrame

pd.concat([s1,s2,s3],axis="columns")

      0     1     2
a     0  <NA>  <NA>
b     1  <NA>  <NA>
c  <NA>     2  <NA>
d  <NA>     3  <NA>
e  <NA>     4  <NA>
f  <NA>  <NA>     5
g  <NA>  <NA>     6

In [75]:
# in this case there is no overlap on the other axis, so as seen above is a union ("outer" join) of the indexes
# can instead intersect them by passing join="inner"
s4 = pd.concat([s1,s3])
s4

a    0
b    1
f    5
g    6
dtype: Int64

In [76]:
pd.concat([s1,s4],axis="columns")

      0  1
a     0  0
b     1  1
f  <NA>  5
g  <NA>  6

In [77]:
pd.concat([s1,s4],axis="columns",join="inner")

   0  1
a  0  0
b  1  1

In [78]:
# a potential issue is that the concatenated pieces are not identifiable in the result
# Suppose instead you wanted to create a hierarchical index on the concatenation axis - use the keys argument
result = pd.concat([s1,s1,s3],keys=["one","two","three"])
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: Int64

In [79]:
result.unstack()

          a     b     f     g
one       0     1  <NA>  <NA>
two       0     1  <NA>  <NA>
three  <NA>  <NA>     5     6

In [80]:
# in the case of combining Series along axis="columns", the keys become the DataFrame column headers:

pd.concat([s1,s2,s3],axis="columns",keys=["one","two","three"])

    one   two  three
a     0  <NA>   <NA>
b     1  <NA>   <NA>
c  <NA>     2   <NA>
d  <NA>     3   <NA>
e  <NA>     4   <NA>
f  <NA>  <NA>      5
g  <NA>  <NA>      6

In [81]:
# the same logic extends to DataFrame objects:
df1 = pd.DataFrame(np.arange(6).reshape(3,2),index=["a","b","c"],
                   columns=["one","two"])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2,2),index=["a","c"],
                   columns=["three","four"])

In [82]:
df1

   one  two
a    0    1
b    2    3
c    4    5

In [83]:
df2

   three  four
a      5     6
c      7     8

In [84]:
pd.concat([df1,df2],axis="columns",keys=["level1","level2"])

  level1     level2
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [85]:
# here the keys argument is used to create a hierarchical index where the first level can be used to identify each of the concatenated DF objects
# if you pass a dictionary of objects instead of a list, the dictionary's keys will be used for the keys option:
# different method, same result

pd.concat({"level1":df1,"level2":df2},
          axis="columns")

  level1     level2
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [86]:
# there are additional arguments governing how the hierarchical index is created
# we can name the created axis levels with the names argument:
pd.concat([df1,df2],axis="columns",
          keys=["level1","level2"],
          names=["upper","lower"])

upper level1     level2
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [87]:
# a last consideration, concerns DataFrames in which the row index does not contain any relevant data:

df1 = pd.DataFrame(np.random.standard_normal((3,4)),
                   columns=["a","b","c","d"])
df2 = pd.DataFrame(np.random.standard_normal((2,3)),
                   columns=["b","d","a"])

In [88]:
df1

          a         b         c         d
0 -0.270266 -2.070846 -1.781814  0.785041
1 -0.559617  0.952516 -0.459913 -0.958845
2  0.894532  1.936760  1.107350  1.134993

In [89]:
df2

          b         d         a
0 -0.638975 -2.162615  2.050953
1  0.546778 -0.107190  0.969806

In [90]:
# in this case (raw index containing no data) can pass ignor_index=True statement; 
# which discards the indexes from each DF and concatenates the data in the columns only, assigning a new default index:
pd.concat([df1,df2],ignore_index=True)

          a         b         c         d
0 -0.270266 -2.070846 -1.781814  0.785041
1 -0.559617  0.952516 -0.459913 -0.958845
2  0.894532  1.936760  1.107350  1.134993
3  2.050953 -0.638975       NaN -2.162615
4  0.969806  0.546778       NaN -0.107190

In [91]:
# pd.concat() functions arguments

# objs : List or dictionary of pandas objects to be concatenated; this is the only required argument
# axis : Axis to concatenate along; defaults to concatenating along rows (axis="index")
# join : Either "inner" or "outer" ("outer" by default); whether to intersect (inner) or union (outer) indexes along the other axes
# keys : Values to associate with objects being concatenated, forming a hierarchical index along the concatenation axis;
#        can be a list or array of arbitrary values, an array of tuples, a lost of arrays (if multiple-level arrays passed in levels)
# levels : Specific indexes to use as hierarchical index level or levels if keys passed
# names : Names for created hierarchical levles if keys and/or levels passed
# verify_integrity : Check new axis in concatenated object for duplicates and raise an exception if so; by default (False) allows duplicates
# ignore_index : Do not preserve indexes along concatenation axis, instead produce a new range (total_length) index

In [92]:
# Combining Data with Overlap
# data combination situation that can't be expressed as either .merge() or .concat()
# two datasets with indexes that overlap in full or in part
# np.where() : performs the array-oriented equivalent of an if-else expression

a = pd.Series([np.nan,2.5,0.0,3.5,4.5,np.nan],
              index=["f","e","d","c","b","a"])
b = pd.Series([0.,np.nan,2.,np.nan,np.nan,5.],
              index=["a","b","c","d","e","f"])

In [93]:
a

f    NaN
e    2.5
d    0.0
c    3.5
b    4.5
a    NaN
dtype: float64

In [94]:
b

a    0.0
b    NaN
c    2.0
d    NaN
e    NaN
f    5.0
dtype: float64

In [98]:
# commanding - where a is NaN, fill it from b values
np.where(pd.isna(a),b,a)

# here, whenever values in a are null, values from b are selected, otherwise the non-null values from a are selected.
# however, using np.where() doesn't check whether the index labels are aligned or not (and doesn't even require the objects to be the same length)

array([0. , 2.5, 0. , 3.5, 4.5, 5. ])

In [99]:
# So, if want to line up values by index, use the Series .combine_first():
a.combine_first(b)

a    0.0
b    4.5
c    3.5
d    0.0
e    2.5
f    5.0
dtype: float64

In [100]:
# with DFs, .combine_first() does the same thing column by column
# this can be a patching method for missing data
df1 = pd.DataFrame({"a":[1.,np.nan,5.,np.nan],
                    "b":[np.nan,2.,np.nan,6.],
                    "c":range(2,18,4)})
df2 = pd.DataFrame({"a":[5.,4.,np.nan,3.,7.],
                    "b":[np.nan,3.,4.,6.,8.]})

In [101]:
df1

     a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [102]:
df2

     a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [103]:
df1.combine_first(df2)

     a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [104]:

# Reshaping and Pivoting

In [105]:
# Reshaping : basic operations for rearranging tabular data
# Reshaping with Hierarchical Indexing
# rearranging data in a DF methods : 
#       1. .stack() : Rotate or pivoting from the columns in the data to the rows
#       2. .unstack() : pivoting from the rows into the columns

In [106]:
# considering a DF with string arrays as row and column indexes
data = pd.DataFrame(np.arange(6).reshape((2,3)),
                    index=pd.Index(["Ohio","Colorado"],name="state"),
                    columns=pd.Index(["one","two","three"],name="number"))
data

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [108]:
# using .stack() on this DF pivots columns into rows, producing a Series:
result = data.stack()
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [110]:
# for heirarchically indexed Series, can rearrange the data back into a DF with .unstack():
result.unstack()

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [113]:
# by defualt, the innermost level is unstacked (same with stack)
# can unstack a different level by passing a level number or name:
result.unstack(level=0)

state   Ohio  Colorado
number
one        0         3
two        1         4
three      2         5

In [114]:
result.unstack(level="state")

state   Ohio  Colorado
number
one        0         3
two        1         4
three      2         5

In [115]:
# unstacking might introduce missing data if all of the values in the level aren't found in each subgroup:
s1 = pd.Series([0,1,2,3],index=["a","b","c","d"],dtype="Int64")
s2 = pd.Series([4,5,6],index=["c","d","e"],dtype="Int64")

In [117]:
data2 = pd.concat([s1,s2],keys=["one","two"])
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

In [118]:
# by default, stacking filters out missing data, so the operation is more easily invertible:
data2.unstack()

        a     b  c  d     e
one     0     1  2  3  <NA>
two  <NA>  <NA>  4  5     6

In [119]:
data2.unstack().stack()

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

In [120]:
data2.unstack().stack(dropna=False)

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_13096\3936770077.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  data2.unstack().stack(dropna=False)

one  a       0
     b       1
     c       2
     d       3
     e    <NA>
two  a    <NA>
     b    <NA>
     c       4
     d       5
     e       6
dtype: Int64

In [121]:
# when using .unstack() in a DF, the level unstacked becomes the lowest level in the result:
df = pd.DataFrame({"left":result,"right":result + 5},
                  columns=pd.Index(["left","right"],name="side"))
df

side             left  right
state    number
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

In [122]:
df.unstack(level="state")

side   left          right
state  Ohio Colorado  Ohio Colorado
number
one       0        3     5        8
two       1        4     6        9
three     2        5     7       10

In [123]:
# as with .unstack(), when calling .stack() we can indicate the name of the axis to .stack():
df.unstack(level="state").stack(level="side")

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_13096\3901086097.py:2: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.unstack(level="state").stack(level="side")

state         Ohio  Colorado
number side
one    left      0         3
       right     5         8
two    left      1         4
       right     6         9
three  left      2         5
       right     7        10

In [125]:
# Pivoting Long to Wide Format

# long or stacked format : common way to store multiple time series in databases and CSV files 
#                          individual values are represented by a single row in a table

data = pd.read_csv("examples/macrodata.csv")

In [126]:
data

,year,quarter,realgdp,realcons,realinv,realgovt,realdpi,cpi,m1,tbilrate,unemp,pop,infl,realint
0,1959,1,2710.349,1707.4,286.898,470.045,1886.9,28.980,139.7,2.82,5.8,177.146,0.00,0.00
1,1959,2,2778.801,1733.7,310.859,481.301,1919.7,29.150,141.7,3.08,5.1,177.830,2.34,0.74
2,1959,3,2775.488,1751.8,289.226,491.260,1916.4,29.350,140.5,3.82,5.3,178.657,2.74,1.09
3,1959,4,2785.204,1753.7,299.356,484.052,1931.3,29.370,140.0,4.33,5.6,179.386,0.27,4.06
4,1960,1,2847.699,1770.5,331.722,462.199,1955.5,29.540,139.6,3.50,5.2,180.007,2.31,1.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,2008,3,13324.600,9267.7,1990.693,991.551,9838.3,216.889,1474.7,1.17,6.0,305.270,-3.16,4.33
199,2008,4,13141.920,9195.3,1857.661,1007.273,9920.4,212.174,1576.5,0.12,6.9,305.952,-8.79,8.91
200,2009,1,12925.410,9209.2,1558.494,996.287,9926.4,212.671,1592.8,0.22,8.1,306.547,0.94,-0.71
201,2009,2,12901.504,9189.0,1456.678,1023.528,10077.5,214.469,1653.6,0.18,9.2,307.226,3.37,-3.19
202,2009,3,12990.341,9256.0,1486.398,1044.088,10040.6,216.385,1673.9,0.12,9.6,308.013,3.56,-3.44

In [127]:
data = data.loc[:,["year","quarter","realgdp","infl","unemp"]]
data

     year  quarter    realgdp  infl  unemp
0    1959        1   2710.349  0.00    5.8
1    1959        2   2778.801  2.34    5.1
2    1959        3   2775.488  2.74    5.3
3    1959        4   2785.204  0.27    5.6
4    1960        1   2847.699  2.31    5.2
..    ...      ...        ...   ...    ...
198  2008        3  13324.600 -3.16    6.0
199  2008        4  13141.920 -8.79    6.9
200  2009        1  12925.410  0.94    8.1
201  2009        2  12901.504  3.37    9.2
202  2009        3  12990.341  3.56    9.6

[203 rows x 5 columns]

In [128]:
data.head()

   year  quarter   realgdp  infl  unemp
0  1959        1  2710.349  0.00    5.8
1  1959        2  2778.801  2.34    5.1
2  1959        3  2775.488  2.74    5.3
3  1959        4  2785.204  0.27    5.6
4  1960        1  2847.699  2.31    5.2

In [129]:
# pd.PeriodIndex() : represents time intervals rather than points in time
# to combine the year and quarter columns to set the index to consist of datetime values at the end of each quarter:
periods = pd.PeriodIndex(year=data.pop("year"),
                         quarter=data.pop("quarter"),
                         name="date")
periods

# .pop() : returns a column while deleting it from the DataFrame at the same time

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_13096\1537753364.py:3: FutureWarning: Constructing PeriodIndex from fields is deprecated. Use PeriodIndex.from_fields instead.
  periods = pd.PeriodIndex(year=data.pop("year"),

PeriodIndex(['1959Q1', '1959Q2', '1959Q3', '1959Q4', '1960Q1', '1960Q2',
             '1960Q3', '1960Q4', '1961Q1', '1961Q2',
             ...
             '2007Q2', '2007Q3', '2007Q4', '2008Q1', '2008Q2', '2008Q3',
             '2008Q4', '2009Q1', '2009Q2', '2009Q3'],
            dtype='period[Q-DEC]', name='date', length=203)

In [130]:
data.index = periods.to_timestamp("D")
data.head()

             realgdp  infl  unemp
date
1959-01-01  2710.349  0.00    5.8
1959-04-01  2778.801  2.34    5.1
1959-07-01  2775.488  2.74    5.3
1959-10-01  2785.204  0.27    5.6
1960-01-01  2847.699  2.31    5.2

In [131]:
# selecting a subset of columns and give the columns index the name "item":

data = data.reindex(columns=["realgdp","infl","unemp"])
data

              realgdp  infl  unemp
date
1959-01-01   2710.349  0.00    5.8
1959-04-01   2778.801  2.34    5.1
1959-07-01   2775.488  2.74    5.3
1959-10-01   2785.204  0.27    5.6
1960-01-01   2847.699  2.31    5.2
...               ...   ...    ...
2008-07-01  13324.600 -3.16    6.0
2008-10-01  13141.920 -8.79    6.9
2009-01-01  12925.410  0.94    8.1
2009-04-01  12901.504  3.37    9.2
2009-07-01  12990.341  3.56    9.6

[203 rows x 3 columns]

In [132]:
data.columns.name = "item"
data.head()

item         realgdp  infl  unemp
date
1959-01-01  2710.349  0.00    5.8
1959-04-01  2778.801  2.34    5.1
1959-07-01  2775.488  2.74    5.3
1959-10-01  2785.204  0.27    5.6
1960-01-01  2847.699  2.31    5.2

In [136]:
# lastly, reshape with .stack() - turn the new index levels into columns with .reset_index()
# finally, giving the column containing the data values the name "value":
long_data = (data.stack().reset_index()
             .rename(columns={0:"value"}))
long_data

          date     item      value
0   1959-01-01  realgdp   2710.349
1   1959-01-01     infl      0.000
2   1959-01-01    unemp      5.800
3   1959-04-01  realgdp   2778.801
4   1959-04-01     infl      2.340
..         ...      ...        ...
604 2009-04-01     infl      3.370
605 2009-04-01    unemp      9.200
606 2009-07-01  realgdp  12990.341
607 2009-07-01     infl      3.560
608 2009-07-01    unemp      9.600

[609 rows x 3 columns]

In [137]:
# data is frequently stored this way [Long format] in relational SQL database, 
# as a fixed schema (column names and data types) allows the number of distinct values in the item column to change as data is added to the table
# in previous example, date and item would usually be the primary keys, offering both relational integrity and easier joins
# however, in some cases the data may be more difficult to work in this format
# for some cases you may prefer to have a DF containing one column per distinct item value idexed by timestamps in the date column
# DF's .pivot() performs this transformation:

pivoted = long_data.pivot(index="date",columns="item",values="value")
pivoted.head()

item        infl   realgdp  unemp
date
1959-01-01  0.00  2710.349    5.8
1959-04-01  2.34  2778.801    5.1
1959-07-01  2.74  2775.488    5.3
1959-10-01  0.27  2785.204    5.6
1960-01-01  2.31  2847.699    5.2

In [139]:
# the first two values passed are the columns to be used, respectively, as the row and column index,
# then an optional value column to fill the DF
# suppose you had two value columns that you wanted to rehsape simultaneously:

long_data["value2"]=np.random.standard_normal(len(long_data))
long_data[:10]

        date     item     value    value2
0 1959-01-01  realgdp  2710.349  1.283510
1 1959-01-01     infl     0.000 -0.294113
2 1959-01-01    unemp     5.800  0.533552
3 1959-04-01  realgdp  2778.801  0.613550
4 1959-04-01     infl     2.340 -0.371276
5 1959-04-01    unemp     5.100 -0.873318
6 1959-07-01  realgdp  2775.488 -1.800937
7 1959-07-01     infl     2.740 -0.517448
8 1959-07-01    unemp     5.300 -0.046173
9 1959-10-01  realgdp  2785.204 -0.092019

In [141]:
# by ommitting the last argument, you obtain a DF with hierarchical columns:
pivoted = long_data.pivot(index="date",columns="item")
pivoted.head()

           value                    value2
item        infl   realgdp unemp      infl   realgdp     unemp
date
1959-01-01  0.00  2710.349   5.8 -0.294113  1.283510  0.533552
1959-04-01  2.34  2778.801   5.1 -0.371276  0.613550 -0.873318
1959-07-01  2.74  2775.488   5.3 -0.517448 -1.800937 -0.046173
1959-10-01  0.27  2785.204   5.6  0.267332 -0.092019 -0.853096
1960-01-01  2.31  2847.699   5.2  0.650721  0.487309  0.735783

In [142]:
pivoted["value"].head()

item        infl   realgdp  unemp
date
1959-01-01  0.00  2710.349    5.8
1959-04-01  2.34  2778.801    5.1
1959-07-01  2.74  2775.488    5.3
1959-10-01  0.27  2785.204    5.6
1960-01-01  2.31  2847.699    5.2

In [143]:
# note that .pivot() is equivalent to creating a hierarchical index using .set_index() followed by a call to unstack:
unstacked = long_data.set_index(["date","item"]).unstack(level="item")
unstacked.head()

           value                    value2
item        infl   realgdp unemp      infl   realgdp     unemp
date
1959-01-01  0.00  2710.349   5.8 -0.294113  1.283510  0.533552
1959-04-01  2.34  2778.801   5.1 -0.371276  0.613550 -0.873318
1959-07-01  2.74  2775.488   5.3 -0.517448 -1.800937 -0.046173
1959-10-01  0.27  2785.204   5.6  0.267332 -0.092019 -0.853096
1960-01-01  2.31  2847.699   5.2  0.650721  0.487309  0.735783

In [144]:
# Pivoting Wide to Long Format

# .pd.melt() : inverse operation to .pivot() for DFs
# rather than transforming one column into many in a new DF, it merges multiple columns into one, producing a DF that is long than the input

df = pd.DataFrame({"key":["foo","bar","baz"],
                   "A":[1,2,3],
                   "B":[4,5,6],
                   "C":[7,8,9]})
df

   key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9

In [145]:
# the "key" column may be a group indicator, and the other columns are data values
# when using pd.melt(), must indicate which columns (if any) are group indicators

melted = pd.melt(df,id_vars="key")
melted

   key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6
6  foo        C      7
7  bar        C      8
8  baz        C      9

In [147]:
# using .pivot(), can reshape back to the original layout:
reshaped = melted.pivot(index="key",columns="variable",values="value")
reshaped

variable  A  B  C
key
bar       2  5  8
baz       3  6  9
foo       1  4  7

In [148]:
# since the result of .pivot() creates an index from the column used as the row labels,
# we may want to use .reset_index() to move the data back into a column:

reshaped.reset_index()

variable  key  A  B  C
0         bar  2  5  8
1         baz  3  6  9
2         foo  1  4  7

In [149]:
# can also specify a subset of columns to use as value columns:

pd.melt(df,id_vars="key",value_vars=["A","B"])

   key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6

In [150]:
# pd.melt() can be used without any group identifiers, too:

pd.melt(df,value_vars=["A","B","C"])

  variable  value
0        A      1
1        A      2
2        A      3
3        B      4
4        B      5
5        B      6
6        C      7
7        C      8
8        C      9

In [151]:
pd.melt(df,value_vars=["key","A","B"])

  variable value
0      key   foo
1      key   bar
2      key   baz
3        A     1
4        A     2
5        A     3
6        B     4
7        B     5
8        B     6